### ISSUE TITLE
Product with custom option file upload does not work.

### ISSUE THREAD

**Issue by redati** [magepow/magento-2-ajax-cart#2]
Product with custom option file upload does not work.

**Comment by redati** [comment]
Magento 2.4.2 PHP 7.4
https://ibb.co/m4GcBKB

**Comment by magiccart** [comment]
@redati I have fixed it, please try to install the new version and check again.

**Comment by redati** [comment]
Hello, updated and did not solve.

https://i.ibb.co/pjBV0JG/ajaxcart.jpg

It still has the same error when trying to add a product with customized file options.

I really wanted to be able to contribute, but I'm still learning. The module is very good.

**Comment by redati** [comment]
Sorry, it was resolved yes. Thanks.

...
$ .ajax ({
                     type: 'post',
                     url: addUrl,
                     date: date,
                     showLoader: options.showLoader,
                     dataType: 'json',
                     cache: false,
                    contentType: false,
                   processData: false,

...
